// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clientconfig$0 from "./clientconfig/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as network$0 from "../network/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ActivateProfile(id) {
    return $Call.ByID(115523217, id);
}

/**
 * @param {string} accessToken
 * @returns {$CancellablePromise<void>}
 */
export function BindDoge(accessToken) {
    return $Call.ByID(819966383, accessToken);
}

/**
 * CheckClientConfig 返回某一分类当前配置文件的实时状态；它只读本地文件，不访问上游。
 * @param {string} category
 * @returns {$CancellablePromise<$models.PublicClientConfig>}
 */
export function CheckClientConfig(category) {
    return $Call.ByID(3420125402, category).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CheckForUpdate 查询官方仓库最新稳定版本。后台检查只返回状态，不下载或替换程序。
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckForUpdate() {
    return $Call.ByID(3131002871).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearUsage() {
    return $Call.ByID(2120615497);
}

/**
 * CompleteOnboarding 结束首次启动引导并启用便携数据持久化；跳过和绑定成功都调用此方法。
 * @returns {$CancellablePromise<void>}
 */
export function CompleteOnboarding() {
    return $Call.ByID(3707202435);
}

/**
 * ConfigureClient 备份并写入当前分类的 CodexRelay 地址和本地访问令牌。
 * 它不改变令牌启用映射，调用方完成写入后再执行启用，避免配置失败却显示为已切换。
 * @param {string} category
 * @param {string} profileID
 * @returns {$CancellablePromise<void>}
 */
export function ConfigureClient(category, profileID) {
    return $Call.ByID(3427215176, category, profileID);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProfile(id) {
    return $Call.ByID(1954926051, id);
}

/**
 * DismissDogeNotification 确认一个提醒类别；同类余额或套餐提醒一次性关闭，公告按当前未读项关闭。
 * @param {string} kind
 * @returns {$CancellablePromise<void>}
 */
export function DismissDogeNotification(kind) {
    return $Call.ByID(2622079213, kind);
}

/**
 * DismissDogeTokenSwitch 在当前失败状态持续期间抑制令牌切换提示，并在失败恢复后的五分钟内继续抑制。
 * 抑制状态仅保存在内存中，不修改便携配置；失败状态恢复后会自动清理。
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DismissDogeTokenSwitch(key) {
    return $Call.ByID(93543395, key);
}

/**
 * EditDogeToken 使用本地完整密钥创建或补全本地代理 API，但不改变当前启用映射。
 * 远端 group 不参与本地类别判断；令牌必须先完成本地类别选择。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function EditDogeToken(id) {
    return $Call.ByID(380539881, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function EnableDogeToken(id) {
    return $Call.ByID(2305030420, id);
}

/**
 * FetchProfileModels 获取当前编辑器输入对应的上游模型目录；只读上游，不修改本地配置。
 * @param {$models.ProfileInput} input
 * @returns {$CancellablePromise<$models.PublicModel[]>}
 */
export function FetchProfileModels(input) {
    return $Call.ByID(1085814066, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function GetState() {
    return $Call.ByID(3062805628).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * InstallUpdate 重新确认最新版本后下载并校验 EXE，再交给 Wails helper 原子替换并重启。
 * @returns {$CancellablePromise<void>}
 */
export function InstallUpdate() {
    return $Call.ByID(3330051357);
}

/**
 * MarkDogeAnnouncementsRead 将当前缓存中指定的公告标记为已读，并同步关闭对应公告提醒。
 * @param {number[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function MarkDogeAnnouncementsRead(ids) {
    return $Call.ByID(215903019, ids);
}

/**
 * OpenDogeProfile 使用系统默认浏览器打开二狗子用户中心，令牌生成路径由界面说明固定提示。
 * @returns {$CancellablePromise<void>}
 */
export function OpenDogeProfile() {
    return $Call.ByID(2314786001);
}

/**
 * OpenDogeTopup 使用系统默认浏览器打开二狗子购买入口。
 * 购买地址来自最近一次 `/api/user/topup/info` 同步结果，不接受前端传入的任意 URL。
 * @returns {$CancellablePromise<void>}
 */
export function OpenDogeTopup() {
    return $Call.ByID(3694618354);
}

/**
 * RedeemDoge 使用当前绑定令牌兑换额度；兑换成功后重新同步用户、套餐和购买配置。
 * 兑换码只存在于本次请求体和上游调用栈，不写入配置、日志或返回状态。
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function RedeemDoge(code) {
    return $Call.ByID(1654359792, code);
}

/**
 * ReorderDogeTokens 按二狗子远端令牌 ID 保存主页顺序；名称、分组和 API 密钥只用于展示或访问，
 * 不参与令牌身份定位。
 * @param {string[]} orderKeys
 * @returns {$CancellablePromise<void>}
 */
export function ReorderDogeTokens(orderKeys) {
    return $Call.ByID(310873119, orderKeys);
}

/**
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function ReorderProfiles(ids) {
    return $Call.ByID(107731990, ids);
}

/**
 * @param {$models.ProfileInput} input
 * @returns {$CancellablePromise<void>}
 */
export function SaveProfile(input) {
    return $Call.ByID(1524050041, input);
}

/**
 * SelectDirectory 打开 Wails 原生目录选择器；取消选择返回空字符串且不报错。
 * @param {string} initialDirectory
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory(initialDirectory) {
    return $Call.ByID(1477342492, initialDirectory);
}

/**
 * SetClientConfigPath 保存外部客户端配置目录，并立即返回新的本地检测状态。
 * @param {string} category
 * @param {string} directory
 * @returns {$CancellablePromise<void>}
 */
export function SetClientConfigPath(category, directory) {
    return $Call.ByID(2510123141, category, directory);
}

/**
 * SetClientConfigSkip 保存某一外部客户端是否跳过主界面切换前的配置检查；它不改写外部文件。
 * @param {string} category
 * @param {boolean} skip
 * @returns {$CancellablePromise<void>}
 */
export function SetClientConfigSkip(category, skip) {
    return $Call.ByID(2542801733, category, skip);
}

/**
 * SetDataDirectory 迁移 config.json 和 usage.json，并让当前进程后续读写使用新目录。
 * 目标同名文件不会覆盖；迁移成功后清理旧目录中的两个 CodexRelay 数据文件。
 * @param {string} directory
 * @returns {$CancellablePromise<void>}
 */
export function SetDataDirectory(directory) {
    return $Call.ByID(3032635246, directory);
}

/**
 * @param {number} minutes
 * @returns {$CancellablePromise<void>}
 */
export function SetDogeSyncInterval(minutes) {
    return $Call.ByID(3841417432, minutes);
}

/**
 * SetDogeTokenCategories 保存用户为尚未导入令牌选择的本地 API 类别；远端 group 仍用于权限判断，display_name 只作为界面文案。
 * 已经导入的令牌不能通过该入口改类别，避免绕过编辑页导致启用映射与配置不一致。
 * @param {$models.DogeTokenCategoryInput[]} assignments
 * @returns {$CancellablePromise<void>}
 */
export function SetDogeTokenCategories(assignments) {
    return $Call.ByID(3990315279, assignments);
}

/**
 * @param {network$0.Settings} input
 * @returns {$CancellablePromise<void>}
 */
export function SetNetwork(input) {
    return $Call.ByID(3744998407, input);
}

/**
 * @param {config$0.Preferences} input
 * @returns {$CancellablePromise<void>}
 */
export function SetPreferences(input) {
    return $Call.ByID(3296747907, input);
}

/**
 * SetProxyPort 校验并热切换本地代理监听端口；新端口无法绑定时不修改配置和现有监听。
 * 端口范围为 TCP 的 1-65535；成功后新请求地址立即使用新端口，已有连接由旧服务优雅退出。
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function SetProxyPort(port) {
    return $Call.ByID(1746439210, port);
}

/**
 * SwitchDogeToken 在服务端重新校验提示、类别和可用状态后启用候选令牌。
 * 前端只提交运行时提示 key 与远端令牌 ID，不能借此切换到其他类别或不可用令牌。
 * @param {string} key
 * @param {number} tokenID
 * @returns {$CancellablePromise<void>}
 */
export function SwitchDogeToken(key, tokenID) {
    return $Call.ByID(3647092161, key, tokenID);
}

/**
 * SyncDoge 执行用户主动触发的完整同步；已有令牌密钥也必须重新请求，只有后台定时同步使用元数据模式。
 * @returns {$CancellablePromise<void>}
 */
export function SyncDoge() {
    return $Call.ByID(1536866851);
}

/**
 * SyncDogeAnnouncements 获取公开公告和当前通知；该请求不依赖二狗子账户绑定状态。
 * @returns {$CancellablePromise<void>}
 */
export function SyncDogeAnnouncements() {
    return $Call.ByID(2451788025);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.TestResult>}
 */
export function TestProfile(id) {
    return $Call.ByID(2130459618, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UnbindDoge() {
    return $Call.ByID(3376309228);
}

// Private type creation functions
const $$createType0 = clientconfig$0.PublicClientConfig.createFrom;
const $$createType1 = $models.UpdateInfo.createFrom;
const $$createType2 = $models.PublicModel.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.DesktopState.createFrom;
const $$createType5 = $models.TestResult.createFrom;
