// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * Preferences 保存窗口生命周期、主页类别可见性、默认筛选和恢复策略；不会改变代理运行时路由。
 */
export class Preferences {
    /**
     * Creates a new Preferences instance.
     * @param {Partial<Preferences>} [$$source = {}] - The source object to create the Preferences.
     */
    constructor($$source = {}) {
        if (!("closeToTray" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["closeToTray"] = false;
        }
        if (!("launchAtStartup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["launchAtStartup"] = false;
        }
        if (!("startHidden" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["startHidden"] = false;
        }
        if (!("visibleCategories" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["visibleCategories"] = [];
        }
        if (!("defaultSource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultSource"] = "";
        }
        if (!("defaultCategory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultCategory"] = "";
        }
        if (!("restoreViewMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["restoreViewMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preferences instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Preferences}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("visibleCategories" in $$parsedSource) {
            $$parsedSource["visibleCategories"] = $$createField3_0($$parsedSource["visibleCategories"]);
        }
        return new Preferences(/** @type {Partial<Preferences>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
