// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class Aggregate {
    /**
     * Creates a new Aggregate instance.
     * @param {Partial<Aggregate>} [$$source = {}] - The source object to create the Aggregate.
     */
    constructor($$source = {}) {
        if (!("requests" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requests"] = 0;
        }
        if (!("reportedRequests" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reportedRequests"] = 0;
        }
        if (!("inputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inputTokens"] = 0;
        }
        if (!("outputTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outputTokens"] = 0;
        }
        if (!("cachedTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cachedTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Aggregate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Aggregate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Aggregate(/** @type {Partial<Aggregate>} */($$parsedSource));
    }
}

export class Day {
    /**
     * Creates a new Day instance.
     * @param {Partial<Day>} [$$source = {}] - The source object to create the Day.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {Aggregate}
             */
            this["total"] = (new Aggregate());
        }
        if (!("profiles" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: Aggregate }}
             */
            this["profiles"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Day instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Day}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("total" in $$parsedSource) {
            $$parsedSource["total"] = $$createField0_0($$parsedSource["total"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField1_0($$parsedSource["profiles"]);
        }
        return new Day(/** @type {Partial<Day>} */($$parsedSource));
    }
}

export class Overview {
    /**
     * Creates a new Overview instance.
     * @param {Partial<Overview>} [$$source = {}] - The source object to create the Overview.
     */
    constructor($$source = {}) {
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {Aggregate}
             */
            this["total"] = (new Aggregate());
        }
        if (!("profiles" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: Aggregate }}
             */
            this["profiles"] = {};
        }
        if (!("days" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: Day }}
             */
            this["days"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Overview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Overview}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("total" in $$parsedSource) {
            $$parsedSource["total"] = $$createField1_0($$parsedSource["total"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField2_0($$parsedSource["profiles"]);
        }
        if ("days" in $$parsedSource) {
            $$parsedSource["days"] = $$createField3_0($$parsedSource["days"]);
        }
        return new Overview(/** @type {Partial<Overview>} */($$parsedSource));
    }
}

export class RequestRecord {
    /**
     * Creates a new RequestRecord instance.
     * @param {Partial<RequestRecord>} [$$source = {}] - The source object to create the RequestRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["profileId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["profile"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("usageStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["usageStatus"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["inputTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["outputTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cachedTokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["totalTokens"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequestRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RequestRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RequestRecord(/** @type {Partial<RequestRecord>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Aggregate.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = Day.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
